version: "3.9"

services:
  # --------------------------------
  # Lavalink (Audio node)
  # --------------------------------
  lavalink:
    container_name: lavamusic-lavalink
    image: ghcr.io/lavalink-devs/lavalink:latest
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
      - ./Lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    ports:
      - "2333:2333"
    healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # -------------------------------
  # Postgres (Database)
  # -------------------------------
  postgres:
    container_name: lavamusic-postgres
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: lavamusic
      POSTGRES_PASSWORD: lavamusic
      POSTGRES_DB: lavamusic
    volumes:
      - ./lavamusic-postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U lavamusic"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lavalink

  # --------------------------------
  # LavaMusic (Bot)
  # --------------------------------
  lavamusic:
    container_name: lavamusic
    image: ghcr.io/botxlab/lavamusic:main
    restart: on-failure
    environment:
      - NODES=[{"id":"Local Node","host":"lavalink","port":2333,"authorization":"youshallnotpass","retryAmount":5,"retryDelay":60000,"secure":"false"}]
      - DATABASE_URL=file:./lavamusic-pgdata
    volumes:
      - ./lavamusic-pgdata:/app/lavamusic-pgdata
    depends_on:
      lavalink:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - lavalink

networks:
  lavalink:
    driver: bridge
